### ISSUE TITLE
Limit text input widths makes them bigger

### ISSUE THREAD

**Issue by dracos** [mysociety/noiseworks#84]
https://github.com/mysociety/noiseworks/commit/9fb867bc8cd0ec6b4af304dbf62290021dcb83c8 set a max-width on inputs, but for the date and time inputs it has made them much wider.
![image](https://user-images.githubusercontent.com/154364/146686598-2acabec1-9cae-4529-ae33-8087eb6c67bc.png)

As their smaller widths is also set using max-width, e.g. the `govuk-input--width-2` class sets it to 5.4ex:
![image](https://user-images.githubusercontent.com/154364/146686607-1e1c21b8-78bf-4730-8b39-2585d994846b.png)

**Comment by zarino** [comment]
Damn! Completely forgot about these date inputs.

I guess a quick fix would be to make sure our classes were defined _before_ the govuk ones (probably a bit tricky?).

Or I maybe we make use of the `:not()` selector (supported all the way back to IE9) to prevent matching inputs with custom widths:

```scss
.lbh-input,
.lbh-textarea {
    &:not([class*="govuk-input--width"]) {
        max-width: 30rem;
    }
}
```
